name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install fnm + node
        shell: bash
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y curl unzip

          curl -fsSL https://fnm.vercel.app/install | bash

          echo "$HOME/.local/share/fnm" >> "$GITHUB_PATH"

          export FNM_PATH="$HOME/.local/share/fnm"
          export PATH="$FNM_PATH:$PATH"
          eval "$(fnm env --use-on-cd)"
          fnm --version

          fnm install 24
          fnm use 24

          node -v
          npm -v

      - name: Clone repo + install dependencies
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          git --version

          # Clone this repo at the commit that triggered the workflow
          git clone "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" app
          cd app

          git checkout "${GITHUB_SHA}"

          eval "$(fnm env)"
          fnm use 24

          npm ci
      - name: Run Tests (capture output)
        working-directory: app
        shell: bash
        run: |
          eval "$(fnm env)"
          fnm use 24

          mkdir -p reports
          npm run check | tee reports/test-results.txt

      - name: Upload test file artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: app/reports/test-results.txt
          if-no-files-found: error

  deploy:
    needs: test
    runs-on: [self-hosted, Linux, X64]
    env:
      APP_DIR: /home/ubuntu/ostad-ops-cicd
    steps:
      - name: Download test results artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: artifacts

      - name: Display test results
        shell: bash
        run: |
          set -euo pipefail
          echo "---- test-results.txt ----"
          cat artifacts/test-results.txt
          echo "--------------------------"

      - name: Checkout repo
        shell: bash
        run: |
          cd "$APP_DIR"
          git fetch origin main
          git reset --hard "${GITHUB_SHA}"
          git rev-parse --short HEAD
      - name: Install dependency
        shell: bash
        run: |
          eval "$(fnm env)"
          fnm use 24
          npm install
